### ISSUE TITLE
New users are receving "Invalid OTP" messages

### ISSUE THREAD

**Issue by timcheadle** [simpledotorg/simple-android#201]
Terry just registered (and was approved) as a new user in Staging, but is receiving "OTP does not match, try again" errors just minutes later. I'm not sure what is actually wrong.

**Comment by govindkrjoshi** [comment]
The `otp is invalid` bug is caused because of the old login flow. If the user’s phone number already exists in the DB, the user should be taken to the login flow. The old login flow expects a OTP but from the deeplink that used to be sent to the user (eg: https://simple.org/register?otp=315329). This should not happen when the new login flow is merged into the app.

This is PR with the fix: https://github.com/simpledotorg/simple-android/pull/193
