### ISSUE TITLE
Instruction to setup up JDK 1.8 installation on Windows Machines (Readme)

### ISSUE THREAD

**Issue by KelvnPere** [simpledotorg/simple-android#2071]
Currently the Readme contains instruction on configuring Java Development Kit on a MacOS for those who don't have that installed. Would also be nice to see an instruction on how that can be done for a Windows Machine. 

**Note:** 
Currently there is not yet an official support for Windows using [jEnv](https://www.jenv.be/)

**Comment by vinaysshenoy** [comment]
We currently do not support building on Windows machines since there are a bunch of checks ([LINK](https://github.com/simpledotorg/simple-android/blob/master/quality/pre-push)) that run when we push to the remote repository. This is not currently a priority for us to fix.

However, you should be able to build and run the app on a Linux machine without any issues.

**Comment by KelvnPere** [comment]
Noted
