### ISSUE TITLE
Suggestion[Update Git clone command) Readme

### ISSUE THREAD

**Issue by KelvnPere** [simpledotorg/simple-android#2072]
Probably its just me, but it seems the current command in the documentation for cloning the project to my local machine doesn't seem to work.  The command in the Readme is $ **git clone git@github.com:simpledotorg/simple-android.git** And I get this message. 

![cloo](https://user-images.githubusercontent.com/36895007/98371471-84055280-203c-11eb-8996-d4e8135f58cb.PNG)

I feel it should be changed to **git clone https://github.com/simpledotorg/simple-android.git** in the Readme.

**Comment by KelvnPere** [comment]
Apologies for adding label **bug** to the issue, its not really a bug but a suggestion.

**Comment by msasikanth** [comment]
Hey @KelvnPere, thanks for reporting this. It's intentional, we want people to connect to GitHub using SSH when cloning and contributing. For more information on how to do this, you can refere their docs [here](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh).

**Comment by vinaysshenoy** [comment]
We could update the docs to link to the SSH documentation, I think.

**Comment by KelvnPere** [comment]
Thanks for the explanation @vinaysshenoy @msasikanth
